export type WeaponClass = "foil-youth" | "foil-adult" | "epee" | "saber";
export type SexAtBirth = "male" | "female" | "intersex" | "prefer_not_to_say";
export type ShirtSize = "YXS" | "YS" | "YM" | "YL" | "YXL" | "XS" | "S" | "M" | "L" | "XL" | "XXL" | "XXXL";
export type SignerType = "athlete" | "guardian";

export type Profile = {
  id: string;
  first_name: string;
  last_name: string;
  birthday: string;
  usa_citizen: boolean;
  sex_at_birth: SexAtBirth;
  gender_identity: string | null;
  weapon_classes: WeaponClass[];
  shirt_size: ShirtSize | null;
  contact_email: string;
  contact_phone: string;
  address_line1: string;
  address_line2: string | null;
  city: string;
  state: string;
  zip_code: string;
  membership_season: string | null;
  enrollment_complete: boolean;
  created_at: string;
  updated_at: string;
};

export type EmergencyContact = {
  id: string;
  profile_id: string;
  contact_order: 1 | 2;
  last_name: string;
  first_name: string;
  relationship: string;
  email: string | null;
  email_2: string | null;
  phone: string;
  phone_2: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  state: string | null;
  zip_code: string | null;
  created_at: string;
};

export type MemberMedical = {
  id: string;
  profile_id: string;
  medical_conditions: string | null;
  preferred_medical_system: string | null;
  created_at: string;
  updated_at: string;
};

export type MemberWaiver = {
  id: string;
  profile_id: string;
  season_year: string;
  dmfc_rules_agreed: boolean;
  dmfc_rules_signature: string | null;
  dmfc_rules_signed_at: string | null;
  dmfc_rules_signer_type: SignerType | null;
  usa_fencing_agreed: boolean;
  usa_fencing_signature: string | null;
  usa_fencing_signed_at: string | null;
  usa_fencing_signer_type: SignerType | null;
  created_at: string;
};

export type MembershipFormData = {
  first_name: string;
  last_name: string;
  birthday: string;
  usa_citizen: boolean;
  sex_at_birth: SexAtBirth | "";
  gender_identity: string;
  weapon_classes: WeaponClass[];
  shirt_size: ShirtSize | "";
  contact_email: string;
  contact_phone: string;
  address_line1: string;
  address_line2: string;
  city: string;
  state: string;
  zip_code: string;
  ec1_last_name: string;
  ec1_first_name: string;
  ec1_relationship: string;
  ec1_email: string;
  ec1_phone: string;
  ec1_address_line1: string;
  ec1_address_line2: string;
  ec1_city: string;
  ec1_state: string;
  ec1_zip_code: string;
  ec2_last_name: string;
  ec2_first_name: string;
  ec2_relationship: string;
  ec2_email: string;
  ec2_email_2: string;
  ec2_phone: string;
  ec2_phone_2: string;
  ec2_address_line1: string;
  ec2_address_line2: string;
  ec2_city: string;
  ec2_state: string;
  ec2_zip_code: string;
  medical_conditions: string;
  preferred_medical_system: string;
  dmfc_rules_agreed: boolean;
  dmfc_rules_signature: string;
  dmfc_rules_signer_type: SignerType | "";
  usa_fencing_agreed: boolean;
  usa_fencing_signature: string;
  usa_fencing_signer_type: SignerType | "";
};

export const MEMBERSHIP_SEASON = "2026-27";
