-- Phase 1: observation-request RSVP table
--
-- STATUS: ALREADY APPLIED to the live project. This filename's timestamp
-- (20260601023647) matches the version already recorded in the remote
-- migration ledger, so tooling must treat this file as applied, not pending.
-- Re-running it against live would fail (table/policy/index already exist);
-- it is captured here only so the migrations folder is a faithful rebuild
-- source. Do not edit this file to "fix" it going forward — see
-- 20260704_membership_hardening.sql for the follow-up ALTER that was applied
-- manually on top of this baseline, and README.md for the full status list.

create table public.observation_requests (
  id                        uuid primary key default gen_random_uuid(),
  submission_id             uuid not null,
  created_at                timestamptz not null default now(),
  name                      text not null,
  email                     text not null,
  phone                     text not null,
  visitor_type              text not null check (visitor_type in ('athlete', 'parent')),
  child_name                text,
  visit_date                date not null,
  weapon                    text not null check (weapon in ('foil', 'epee', 'saber')),
  party_size                integer not null default 1 check (party_size > 0),
  notes                     text,
  reminder_sent             boolean not null default false,
  notes_internal            text,
  converted_to_member_id    uuid,
  constraint child_name_required_when_parent
    check (visitor_type <> 'parent' or child_name is not null)
);

alter table public.observation_requests enable row level security;

create index observation_requests_visit_date_idx
  on public.observation_requests (visit_date)
  where reminder_sent = false;

create index observation_requests_submission_id_idx
  on public.observation_requests (submission_id);
